apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: another-long-tenant-name-web
  namespace: argocd
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: another-long-tenant-name
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: web
      images:
        - alias: web
          imageName: ghcr.io/notniknot/web-apps:main
          manifestTargets:
            kustomize:
              name: ghcr.io/notniknot/web-apps
          commonUpdateSettings:
            updateStrategy: digest
            forceUpdate: true
            allowTags: regexp:^main$
            pullSecret: pullsecret:argocd/ghcr-pull-secret
            platforms:
              - linux/amd64
