apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-new-app-name-is-long
  namespace: another-long-tenant-name
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: another-long-tenant-name
  sources:
    - repoURL: https://github.com/notniknot/another-long-tenant-name-config.git
      targetRevision: main
      path: apps/my-new-app-name-is-long/playground
      kustomize: {}
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: 6.7.1
      helm:
        releaseName: my-new-app-name-is-long-addon
        valuesObject:
          replicaCount: 1
          logLevel: info
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: another-long-tenant-name
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
    retry:
      refresh: true
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
