apiVersion: v1
kind: ConfigMap
metadata:
  name: preview-params
  labels:
    preview.sonia.so/contract: params
data:
  previewID: local
  hostname: my-new-app-name-is-long-local.sonia-certs.uk
  applicationName: another-long-tenant-name-preview-local
  imageAllowTags: regexp:^preview-local-.*
  appName: my-new-app-name-is-long-local
  generatedMessage: local-message
